#!/usr/bin/env ruby

exit if ENV['AUTO_MIGRATE'] == '0'
raise 'Ruby >= 1.9 required' unless (RUBY_VERSION.split('.').map(&:to_i) <=> [1, 9]) >= 0

operation = ARGV.shift
exit unless operation == 'rebase'

require_relative "lib/git"
require_relative "lib/schema"

from = "#{gets.split(' ')[1]}^"

migrations = Git.changes_in(Schema::MIGRATIONS_PATH, from, 'HEAD', 'A')

Schema.print_plan(:migrations => migrations)

if migrations.any?
  Git.within_sandbox do
    Schema.migrate(migrations)
  end
end
