#!/usr/bin/env ruby

rollbacks = []
migrations = []

`git diff --name-status HEAD@{1} HEAD db/migrate/`.split("\n").each do |line|
  status, file = line.split("\t")
  rollbacks <<= file if status == "D"
  migrations <<= file if status == "A"
end

puts "Migrating:  #{migrations.count} up, #{rollbacks.count} down"

