#!/usr/bin/env ruby

exit if ENV['AUTO_MIGRATE'] == '0'

operation = ARGV.shift
exit unless operation == 'rebase'

require_relative "lib/git"
require_relative "lib/schema"

from = "#{gets.split(' ')[1]}^"

migrations = Git.changes_in(Schema::MIGRATIONS_PATH, from, 'HEAD', 'A')

puts "Migrating:  #{migrations.count} up"
Schema.migrate(migrations)
