#!/usr/bin/env ruby

@from, @to, flag = ARGV
exit unless flag == '1' && @to != @from

require_relative "lib/git"
require_relative "lib/schema"

path = 'db/migrate/'
ancestor = Git.common_ancestor(@from, @to)
rollbacks = Git.changes_in(path, ancestor, @from, 'A')
migrations = Git.changes_in(path, ancestor, @to, 'A')

puts "Migrating:  #{rollbacks.count} down, #{migrations.count} up"

unless rollbacks.empty?
  Git.checkout(@from, rollbacks)
  Schema.rollback(rollbacks)
  Git.reset
end

Schema.migrate(migrations)
